#pragma once

enum Constants {
    BACKGROUND_WIDTH = 1000,
    BACKGROUND_HEIGHT = 560,
    BUCKET_WIDTH = 150,
    BUCKET_HEIGHT = 150,
    BUCKET_STEP = 25,
    RAINDROP_WIDTH = 30,
    RAINDROP_HEIGHT = 50,
    RAINDROP_SPEED = 50,
    RAINDROP_COUNT = 10,
    COLLISION_INTERVAL = 50,
};
